version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/admin"
    schedule:
      interval: "weekly"
