default_language_version:
    python: python3.8
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-merge-conflict
          - id: check-added-large-files
          - id: check-ast
          - id: check-symlinks
          - id: check-yaml
          - id: trailing-whitespace
          - id: check-json
          - id: debug-statements
          - id: pretty-format-json
            args: ["--autofix", "--allow-missing-credentials"]
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: ["--profile", "black"]
    - repo: https://github.com/PyCQA/flake8
      rev: "7.0.0"
      hooks:
          - id: flake8
            additional_dependencies: [flake8-print]
            files: '\.py$'
            args:
                - --select=F401,F403,F406,F821,T001,T003
    - repo: https://github.com/humitos/mirrors-autoflake
      rev: v1.1
      hooks:
          - id: autoflake
            files: '\.py$'
            exclude: '^\..*'
            args: ["--in-place", "--remove-all-unused-imports"]
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
            args: ["--target-version", "py38"]
