"""P5 audit_logs drop FKs

Revision ID: 790160f63ff0
Revises: d5a5e57d9e13
Create Date: 2026-04-30 13:38:28.411708

"""

from collections.abc import Sequence

from alembic import op


revision: str = "790160f63ff0"
down_revision: str | None = "d5a5e57d9e13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("audit_logs_org_id_fkey"), "audit_logs", type_="foreignkey")
    op.drop_constraint(op.f("audit_logs_actor_id_fkey"), "audit_logs", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("audit_logs_actor_id_fkey"), "audit_logs", "users", ["actor_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        op.f("audit_logs_org_id_fkey"), "audit_logs", "organizations", ["org_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
