"""P10 ai_threads ai_messages

Revision ID: 91177bbb192d
Revises: a3ebab3d4846
Create Date: 2026-04-30 13:51:38.121575

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "91177bbb192d"
down_revision: str | None = "a3ebab3d4846"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_threads",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_threads_org_id"), "ai_threads", ["org_id"], unique=False)
    op.create_index("ix_ai_threads_org_user", "ai_threads", ["org_id", "user_id"], unique=False)
    op.create_table(
        "ai_messages",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.Integer(), server_default="0", nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["ai_threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_messages_created_at"), "ai_messages", ["created_at"], unique=False)
    op.create_index("ix_ai_messages_thread_created", "ai_messages", ["thread_id", "created_at"], unique=False)
    op.create_index(op.f("ix_ai_messages_thread_id"), "ai_messages", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_messages_thread_id"), table_name="ai_messages")
    op.drop_index("ix_ai_messages_thread_created", table_name="ai_messages")
    op.drop_index(op.f("ix_ai_messages_created_at"), table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index("ix_ai_threads_org_user", table_name="ai_threads")
    op.drop_index(op.f("ix_ai_threads_org_id"), table_name="ai_threads")
    op.drop_table("ai_threads")
    # ### end Alembic commands ###
