"""P10b ai message cost and metadata

Revision ID: d5ae679a86c1
Revises: 91177bbb192d
Create Date: 2026-04-30 16:01:40.513498

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "d5ae679a86c1"
down_revision: str | None = "91177bbb192d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_messages", sa.Column("cost_usd", sa.Numeric(precision=20, scale=10), server_default="0", nullable=False)
    )
    op.add_column("ai_messages", sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column(
        "ai_messages", "model", existing_type=sa.VARCHAR(length=64), type_=sa.String(length=120), existing_nullable=True
    )
    op.add_column("ai_threads", sa.Column("default_model", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_threads", "default_model")
    op.alter_column(
        "ai_messages", "model", existing_type=sa.String(length=120), type_=sa.VARCHAR(length=64), existing_nullable=True
    )
    op.drop_column("ai_messages", "extra")
    op.drop_column("ai_messages", "cost_usd")
    # ### end Alembic commands ###
